environments:
  default_migration_table: phinxlog
  default_database: development
  development:
      adapter: mysql
      host: localhost
      name: development_db
      user: user
      pass: ''
      port: 3306
      charset: utf8
      collation: utf8_unicode_ci
  production:
      adapter: mysql
      host: localhost
      name: production_db
      user: user
      pass: ''
      port: 3306
      charset: utf8
      collation: utf8_unicode_ci
paths:
    migrations: /var/www/fuchsia_framework/migrations